name: CD
run-name: Running deployment 🚀
on:
  push:
    branches: [v2]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MUTANT_HOST }}
          username: ${{ secrets.MUTANT_USERNAME }}
          key: ${{ secrets.MUTANT_SECRET }}
          port: ${{ secrets.MUTANT_PORT }}
          script: |
            cd repositories/airmutasi-laravel
            git pull origin v2
            npm run build
